/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Timestamp = ColumnType<Date | string>;

export interface Article {
  body: string;
  createdAt: Timestamp;
  description: string;
  id: string;
  slug: string;
  title: string;
  updatedAt: Timestamp;
}

export interface Tags {
  articleId: string;
  name: string;
}

export interface DB {
  article: Article;
  tags: Tags;
}
